# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  # mmd of 0.015 gets higher performance but slower run time
  max_match_distance: 0.01  # = 1cm
  tolerances:
    patch:
      pose_vectors: ${np.list_eval:[50 * np.pi / 180, 50 * np.pi / 180, 50 * np.pi / 180]}
  feature_weights: {}
  # smaller threshold reduces runtime but also performance
  x_percent_threshold: 20
  # Update all hypotheses with evidence > 80% of max evidence (faster).
  evidence_threshold_config: 80%
  use_multithreading: false
  # NOTE: Not used when loading pretrained graphs.
  max_graph_size: 0.3  # 30cm
  num_model_voxels_per_dim: 100
  # Using a smaller max_nneighbors (5 instead of 10) makes runtime faster, but reduces
  # performance a bit.
  hypotheses_updater_args:
    max_nneighbors: 10
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
